ORNL/cpp-proposals-pub

- P0009/P0009.bs
`X const&` -> `const X&` (for various X).
This change makes the document more consistent with both the standard, and with itself.
> P0009: "X const&" -> "const X&"

- P0009/P0009.bs
1. `template <` -> `template<`
2. `template<typename` ->`template<class`
This imitates what the standard does, and also makes the document internally consistent.
> P0009: template parameter format fixes

- P0009/P0009.bs
This unfortunately requires a `<pre>` block instead of triple-backticks or `<xmp>`, hence the removal of left angle brackets.
> P0009: Italicize "exposition only" comments

- P0009/P0009.bs
get_ is not a common naming scheme for observer functions.
Thus rename stuff like get_extents, get_strides, get_mapping,
get_accessor. Based on hcedwar pull request, but splitting it out
into smaller pieces.
Note that this fixes a number of instances where renames were not fully propagated through the wording for mapping and accessor. I hope I caught all of them by stepping to every single one ...
> P0009: Renaming get_ functions

- P0009/P0009.bs
This is based on PR55 cleans some stuff up etc. In particular: since we figured out what Carter wanted to call an accessor is actually pretty much a smart pointer in c++ (such as shared_ptr in C++ 11 which actually doesn't have a [] operator and doesn't fulfill random access iterator) I went back to calling it pointer. `decay` simply returns a `element_type*`, and everything else seems to fall nicely into place. I also removed the constructors taking a `span` since we don't require that `pointer` is constructible from `element_type*` alone.
> P0009 define new accessor_policy based on PR55

- P0009/reference-implementation/include/extents.hpp
This fix this error with g++-8:
.../cpp-proposals-pub/P0009/reference-implementation/include/extents.hpp:72:10: error: template argument ‘(int)R’ involves template parameter(s)
struct extents_analyse<R,dynamic_extent,StaticExtents...> {
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> Make a template parameter uniform by using int everywhere

- P0009/reference-implementation/include/extents.hpp
- P0009/reference-implementation/test/test_extents.cpp
Static and non-static extents with r >= rank() are specified to be 1
> P0009 reference extents

- P0009/reference-implementation/include/mdspan.hpp
mdspan::perator[] to use AccessPolicy::access method.
Commented out mdspan::span() to use AccessPolicy::decay and Layout::Mapping::required_span_size
> P00009 reference 

- P0009/P0009.bs
@crtrott @dhollman 
SAN2018 LWG small group discussion points addressed in this commit:
(Everything before "Header synopsis" section in minutes)
* "Add the following paragraphs to `[views.general]`" needs to say where in that section it's added. It currently consists of one paragraph. Would be good to depict this as the existing section with green text for insertion, just for context. Helpful to have that when editing something that exists.
- Clarified insertion point
* This seems like the wrong place for that text: "The `basic_mdspan` object ... is a span of elements." Detailed explanation of mdspan that would be separated by lots of text. Move to before synopsis of mdspan. Same for this (the subspan function). Only first sentence of that paragraph should stay in [views.general].
- Moved …
> P0009: More fixes for pre-Kona 2019 mailing

- D1673/blas_interface.md
@crtrott @dalg24 @dhollman et alia: Most important changes:
* Finished wording for `layout_blas_general` and `layout_blas_packed`
* Moved or removed most non-wording introductory material out of the wording section
* Made explicit where the wording section starts, by putting wording in a new section called "Wording"
* (new as of 2020 Jan 07 AM) finished adding a synopsis and section headers
> P1673R2: 2020 Jan 06 wording changes

- P0009/P0009r12.md
- P0009/generated/P0009r12.html
R12 changes:
- Fixed definition of `static_extent`
- Added converting constructor for `default_accessor` (when the pointers to
elements are convertible) for things like `default_accessor<double>` to `default_accessor<const double>`
- Changed [mdspan.accessor.basic] to [mdspan.accessor.default], to correspond with the name change
in P0009r11
- Minor formatting corrections
> P0009R12 mdspan

- P0009/P0009.md
@crtrott @dalg24 @nliber @brycelelbach 
Edited: Remove all `noexcept` from `mdspan`, per current library wording guidance.  Please see, e.g., [P0884r0](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0884r0.pdf).  Leave noexcept everywhere else without changes.
~Make all of `mdspan`'s public methods conditionally `noexcept`.  This is based on PR #155 (please merge that first; thanks!).~
~This does not yet have the `operator[]` changes due to P2128.  That should make the uncertainty about how to `noexcept`-ify single-index `operator[]` go away (since single-index `operator[]` will go away).~
> P0009: Remove noexcept from mdspan

- P0009/P0009.md
The wording didn't take into account a situation where one of the extents is 0.
It also didn't take into account rank-0 mdspan.
> Fix required_span_size for degenerated mdspan and rank-0 mdspan

- P0009/P0009.md
@crtrott @nliber @dalg24 
* Use `operator[]` in `mdspan` for multidimensional array access,
add explanation to Discussion section, and fix all the examples
* Remove reference to `span` in the `mdspan` wording,
since `mdspan` does not necessarily require a backing `span`
(because `pointer` need not be `ElementType*`)
> P0009: Add operator[]; remove reference to "span"

- P0009/P0009.md
- makes mdspan, mapping and accessor constructors conditionally explicit
- makes extents conversion constructor explicit for dynamic -> static
- fixes the pointer derived to base class assignment for
default_accessor
> Make constructor conditionally explicit

- P0009/P0009.md
Allow strides std::array to be any size type convertible.
I.e. follow other places where we take arrays.
> Fix layout_stride constructor for flexible stride array

- P0009/P0009.md
Nasos and John have a requirement to put their affiliations on the proposal.  This PR implements that.
> Add affiliations to some authors per request

- P0009/P0009.md
@crtrott 
1. Remove e-mails of two authors (but retain affiliations) per request.
2. Update "audience" field in top matter from LWG to LEWG.
> P0009: Remove e-mails per request; update audience

- P0009/P0009.md
@crtrott @dalg24 @nliber 
1. Fix accessor policy wording, in particular the bulleted list
that wasn't lining up with the table.
2. Remove implications that the set of elements that an accessor
accesses is contiguous in memory.  (It need not be.)
> P0009: Fix accessor policy; stop implying "contiguous"-ness

- P0009/P0009.md
For non-contiguous unique mappings required_span_size can be used.
For unique mdspans/mappings size can be used.
> unique_size is unimplementable for non-unique non-contiguous

- P0009/P0009.md
The codomain of an `mdspan` isn't necessarily a `span`.
> P0009: Remove incorrect reference to `span`

- P0009/P0009.md
For consistency with `extents::rank[_dynamic]`
> Let `mdspan::rank[_dynamic]` return `size_t`

- P0009/P0009.md
I guess this is the intended behavior, although the layout mapping requirements table doesn't show `op==`, so it's not clear what the semantics are supposed to be in general.
> P0009: `operator==` for `layout_stride` should consider strides

- P0009/P0009.md
I mentioned to @crtrott by private email that I was working on an `mdspan` implementation. I'm still implmenting `submdspan`, but I think I've now read all the wording closely enough to offer a single set of wording suggestions. From the changelog:
- Consistently use "`<`_expr_`>` is `true`" instead of "`<`*expr*`>` is true".
- In the layout mappings' `operator()` *Effects* clauses, use only `index_sequence`and fix syntax error in `stride(P())`.
- Replace various unary folds with binary to handle `extents<>`.
- Consistently use `Extents::rank()` in layout mapping wording.
- Typo in `mdspan::mapping_type`: `template mapping_type` should be `template mapping`.
- `mdspan`'s `array` constructor calls `Extents`'s `array` constructor.
- Clarify the value of `static_stride` for `submdspan`'s …
> P0009: misc. wording suggestions

- P0009/P0009.md
This follows guidance that all expositon only names should be cursive themselves.
> Exposition only rename

- P1684-mdarray/P1684.html
- P1684-mdarray/P1684.md
Changes:
* add new `mdarray` constructors from `mdspan`
* add `view` member function; it returns an `mdspan` that views the `mdarray`'s elements
Wording for the new `mdarray(mdspan)` constructors needs review.  The issue is that may not be able to construct the `mdarray`'s container directly from an input range, because the input's `required_span_size()` may be bigger than the number of elements in the container.  There are two ways to deal with that:
1. construct the container to have the right size, with default-constructed elements, then loop over the unique `i...` in its domain and assign from `input[i...]` to the container; or
2. use `ranges::to` initialization of the container.
Option (2) implies using ranges to iterate over the input `mdspan`.  We don't want to require that. …
> P1684: R2 changes

- D1674/evolving-from-blas.md
@crtrott @dalg24 @nliber 
PR https://github.com/ORNL/cpp-proposals-pub/pull/228 by Jeff Hammond suggests changes to P1673.  Some of those can be applied to P1674 as well.  This PR does that.  I also took the opportunity to make a few minor drive-by fixes.
> P1674: Changes based on PR suggestions for P1673

- D1673/P1673.bs
Fix typo in `givens_rotation_setup` for complex numbers.
Fixes #230.
> P1673: Fix givens_rotation_setup typo

- D1673/P1673.bs
@crtrott @dalg24 @nliber 
* Add intro wording explaining the design
* Make sure `accessor_conjugate` and `conjugated` work correctly for user-defined complex types
* Introduce _`conj-if-needed`_ to simplify wording
* Resolve vagueness in return type of `conjugated`
* Add acknowledgments for Yu You and Phil Miller
* Add R8 submission date
* Update my e-mail address
Fixes #236.
Addresses part of https://github.com/kokkos/stdBLAS/issues/189.
> P1673: Fix wording for user-defined complex types

- P0009/P0009.md
Don't cast to size_type before invoking operator[](indices...),
so that operator[](indices...) can check preconditions.
Also, fix example in non-wording section to include IndexType
template arguments for extents.
> P0009: Fix operator[](span-or-array)

- submdspan/submdspan.md
@crtrott @nliber @dalg24 
* Preconditions on slice integers now use "representable as a value of type `index_type`," just as indexing does for mdspan.
* Fix associated Constraints and Mandates clauses.
* Make other small fixes, and renumber.
> submdspan: Impose "representable as index_type" preconditions

- D1673/P1673.bs
- D1673/P1673R10.html
Revisions for P1673R10, including changing `pointer` in the proposed accessors to `data_handle_type`, to match the mdspan specification.
> P1673R10: pointer -> data_handle_type

- layout_padded/D2642R1.html
- layout_padded/P2642R1.html
- layout_padded/layout_padded.bs
Change padding stride to function as an overalignment factor if less than the extent to pad.
Remove mapping constructor that takes `extents_type` and `extents<index_type, padding_stride>`, because the latter may not be the actual padding stride.
Update the non-wording sections to match the above changes.
Make other minor content and formatting fixes.
> P2642R1 revisions

- D1673/.gitignore
- D1673/Makefile
- D1673/P1673.md
@crtrott @dalg24 
* Make document build with Pandoc and produce reasonable output.  (Pandoc conversion is ongoing; its completion can be deferred to future pull requests.)
* Replace name-based mdspan requirements with exposition-only concepts.
* Experimentally simplify `*_matrix_vector_product` wording (please review that part with care).
> P1673: Start on R11 changes and Pandoc-ification

- D1673/P1673.md
@crtrott @dalg24 
* Remove Constraints made redundant by the new exposition-only concepts.
* Follow LEWG guidance to simplify Effects and Constraints
(e.g., removing wording referring to the
"the mathematical expression for the algorithm")
by describing them mathematically (in math font).
("Mathematical expression for the algorithm"
remains in a few places that call for more careful analysis.)
* Change `matrix_one_norm` Precondition (that the result of
`abs` of a matrix element is convertible to `T`) to a Constraint.
* Change `vector_abs_sum` Precondition (that the result of
`init + abs(v[i])` is convertible to `T`) to a Constraint.
* Address [issue](https://github.com/ORNL/cpp-proposals-pub/pull/314#issuecomment-1370334893) with constraints for symmetric and Hermitian update algorithms. …
> P1673: Address constraints issue; fix some formatting

- atomic_accessor/atomic_accessor.html
- atomic_accessor/atomic_accessor.md
Added `atomic-ref-bounded` exposition-only template for an `atomic_ref` like type bounded to a particular `memory_order`
Added `atomic_ref_relaxed`, `atomic_ref_acq_rel` and `atomic_ref_seq_cst` alias templates
Added `basic-atomic-accessor` exposition-only template
Added `atomic_accessor_relaxed`, `atomic_accessor_acq_rel` and `atomic_accessor_seq_cst` templates
> P2689R1 Atomic Refs Bounded to Memory Orderings & Atomic Accessors

- batched_blas/P2901R0.html
- batched_blas/batched_blas.md
@crtrott Per our discussion this afternoon, I've fixed the `scaled(alpha, A)` discussion in the batched BLAS paper.  It explains why `scaled` cannot take an array or mdspan of scaling factors, and therefore that the multiple-scaling-factors case needs overloads that take the scaling factors explicitly.
I've also removed the stub sections and added some links to existing vendor libraries.  The paper is ready for submission, though it could still use more work.
> Fix scaled(alpha, A) discussion in batched BLAS paper

- layout_padded/P2642R3.html
- layout_padded/layout_padded.md
I submitted this as R3 of P2642.  Tasks:
We'll also need to look at overload resolution for `submdspan_*` overloads for these new mapping types.  That's not really a design change (at least not a design intent change), so I think it's OK to defer that until LWG review.
@crtrott @dalg24
> P2642R3: Version I submitted

- layout_padded/P2642R3.html
- layout_padded/layout_padded.md
In P2642, change `extents()` return type from `extents_type` to `const extents_type&`.  Add design explanation and credit Oliver Lee for discussion.  Fix some minor formatting issues.  Rerender the document.
> P2642: Fix extents() return type

- D1673/D1673R13-running-revision.html
- D1673/P1673.md
This implements changes discussed in LWG 2023/09/20, and resolved via later e-mail list discussion.
Define what it means for two mdspan to "overlap" each other.  Replace "shall view a disjoint set of elements of" wording (was [linalg.concepts] 3 in R12) with "shall not overlap." "Alias" retains its R12 meaning (view the same elements in the same order).  This lets us retain existing use of "alias" in describing algorithms.
> P1673: Fix "alias"

- D1673/D1673R13-running-revision.html
- D1673/P1673.md
Revise wording of "alias" and "overlap," based on feedback from 2023/09/27 LWG meeting.
Fixes #406.
> P1673: Revise "alias" and "overlap" wording

- aligned_accessor/P2897R1.html
- aligned_accessor/aligned_accessor.md
> P2897 (aligned_accessor): R1
