P0009/P0009.bs

I kinda am at this point so there it is

P0009: Add self as editor

---

P0009/P0009.bs

P0009: Reword accessor concept a(p,i) note

---

P0009/P0009.bs

P0009: mdspan fixes, part 1

---

P0009/P0009.bs

P0009: Minor syntax fix in accessor Note

---

P0009/P0009.bs

P0009: Add section headings to synopses

---

P1348/p1348.bs

Added paper prepared in situ at San Diego meeting

P1348 executor occupancy

---

P0009/P0009.bs

This PR supersedes PR https://github.com/ORNL/cpp-proposals-pub/pull/90 .
It implements the changes in that PR, plus suggestions in the comments, plus minor grammar and wording fixes.
@hcedwar @dsunder @dhollman

P0009: Wording updates from PR #90, plus suggestions & minor fixes

---

D1673/blas_interface.md

P1673R2: Remove "functions not in Reference BLAS" from future work

---

D1673/blas_interface.md

@crtrott @dalg24 
Also add explanation why we removed this requirement.

P1673R2: Remove over/underflow requirement for vector_norm2

---

D1673/blas_interface.md

P1673R2: Check compile-time extents via Mandates clause

---

D1673/blas_interface.md

Add missing function `triangular_matrix_product`.  Thanks to Peter Caday for pointing this out!
@crtrott @dalg24

P1673R2: Add triangular_matrix_product

---

D1673/blas_interface.md

P1673R2: Review 2020 Jan 03

---

D1673/blas_interface.md

P1673R2: Changes based on 2020 Jan 03 review

---

D1673/blas_interface.md

@crtrott @dalg24 Nevin @dhollman all of my peeps :)

P1673R2: Update date; make {scaled,conjugated}_scalar exposition only

---

D1673/blas_interface.md

@crtrott @dalg24 @dhollman and friends :-D

P1673R2: #126, plus fixes & Cholesky factorization example

---

D1673/blas_interface.md

@crtrott please review; thanks! : - )

D1673R3: Add conceptification section; add Alicia Klinvex as coauthor; minor revisions

---

P1370/numeric_limits_experiences.txt

@dalg24 This is the original version of the paper that I sent you.  I have not yet made revisions.  Thanks!

P1370: Add first draft of numeric_limits experiences paper

---

D1673/blas_interface.md

1. Fix Bryce's name and e-mail address, per his request today.
2. Revise proposal due to P0009 changes (esp. `ptrdiff_t` -> `size_t`).

Fix author list; make changes due to P0009R11 changes

---

D1673/blas_interface.md

stdBLAS: add template parameter to ssq result

---

D1673/blas_interface.md

1. Fix Dan Sunderland's contact info
2. Incorporate changes from P0009R12 and P2299R3
3. Update other references and quotes from those references to their latest versions

P0009R12 and P2299R3 updates

---

P0009/P0009r12.md

Incorporate changes proposed by P2299R3, and make a few minor fixes.

P0009R13: Incorporate p2299r3 changes

---

P0009/P0009.md

This PR supersedes https://github.com/ORNL/cpp-proposals-pub/pull/150 and https://github.com/ORNL/cpp-proposals-pub/pull/154.  It improves the Description section of P0009 in preparation for R13.

P0009: Improve description

---

D1673/P1673.bs
D1673/blas_interface.md

related to: https://github.com/kokkos/stdBLAS/issues/100 @mhoemmen

P1673: dotc: conjugate first argument

---

P0009/P0009.md

Also add missing changelog entry for fixing layout_stride operator==
Addresses #187

Fix layout_stride required_span_size

---

P0009/P0009.html
P0009/P0009.md

Addresses more stuff from #200

Review 2022 02 18

---

P1684-mdarray/P1684.md

1. Fix author list
2. Update and simplify the front matter (not the Wording) for P000916

Update P1684 front matter and author list

---

P0009/P0009.html
P0009/P0009.md

P0009 lwg 04 01 review

---

D1673/P1673.bs

This supersedes PR https://github.com/ORNL/cpp-proposals-pub/pull/186 (which hasn't gotten merged yet).
I submitted this tonight as P1673R7.

P1673R7 changes by mhoemmen

---

D1674/evolving-from-blas.md

Update P1674 for R1 submission for April 2022 mailing.
* Clean up Markdown formatting
* Update links and references
* Account for P2128 (multidimensional `operator[]`),
which WG21 adopted on 2021-10
* Account for changes to P1673 and other proposals in flight

P1674: Updates for R1

---

D1673/P1673.bs

P1673: Remove unused line of code from example

---

D1673/P1673.bs

P1673: Fix typo "TLE" -> "TLB"

---

P0009/P0009.html
P0009/P0009.md
P2553/P2553.html
P2553/P2553.md

This implements all the notes made for the LWG small group meeting on 2022-05-24 noted here: #247 except adding swap

Lwg 22 05 24

---

P0009/P0009.md
P2553/P2553.md

These changes come from LWG small group review of P2553 on 2022/05/31.  LWG small group also suggested changes to P0009.
NOTE: LWG small group has suggested merging P2553 into P0009.  This PR does NOT implement that.  The P0009 changes are separate suggestions from LWG that are unrelated to P2553.
@crtrott @dalg24 @nliber

P2553, P0009: LWG small group review 2022/05/31

---

D1673/P1673.bs
D1673/P1673R9.html

This PR includes all the changes for P1673R9.

P1673: R9 changes

---

P0009/P0009.html
P0009/P0009.md

Lwg review 04 24

---

submdspan/submdspan.md

submdspan: Revise non-wording part of paper

---

submdspan/submdspan.md

submdspan: Update my e-mail address

---

submdspan/submdspan.md

@crtrott @dalg24 @nliber Add `strided_index_range` nonwording explanations.
* Why we want template argument deduction to work
* Why we want the type to be an aggregate
* How to get most of those features if the compiler doesn't support template argument deduction for aggregates

submdspan: Add strided_index_range explanations

---

layout_padded/P2642R0.html
layout_padded/build.sh
layout_padded/layout_padded.bs
layout_padded/layout_padded.html

1. Add new mdspan layouts `layout_left_padded` and `layout_right_padded`
2. Add support for those layouts in submdspan
3. Change submdspan of `layout_left` resp. `layout_right` to produce `layout_left_padded` resp. `layout_right_padded` if possible

[REVIEW] layout_left_padded & layout_right_padded

---

D1673/P1673.bs
D1673/P1673R10.html

@crtrott and I went through part of the P1673 wording today.  We fixed some things and marked others for later revision.  We have more work to do yet before this should be submitted as P1673R10.
* Revise `scaled` and `conjugated` wording.
* Make all matrix view functions `constexpr`.

P1673R10 revisions

---

layout_padded/D2642R2.html
layout_padded/layout_padded.bs

P2642 R2 updates started 2022/12/28 and finished 2022/12/29.  @crtrott , please review; thanks!
This PR does NOT attempt to reformat from Bikeshed to Pandoc.  It only makes changes to content (mostly wording).

P2642: R2 update (2022/12/28 - 2022/12/29)

---

D1673/P1673.md

P1673: Pandoc reformatting; add paragraph numbers

---

layout_padded/Makefile
layout_padded/P2642R2.html
layout_padded/layout_padded.bs
layout_padded/layout_padded.md

@crtrott @dalg24 @nliber This is ready for review now; thanks!

P2642R2: Changes from 2023/01/13 review

---

aligned_accessor/Makefile
aligned_accessor/P2897R0.html
aligned_accessor/README
aligned_accessor/aligned_accessor.md

I plan to finish this today.  It's still a draft, because I need to finish formatting.
Fixes https://github.com/ORNL/cpp-proposals-pub/issues/370

Add aligned_accessor proposal

---

batched_blas/P2901R0.html
batched_blas/batched_blas.md

This is the version of P2901R0 (Batched BLAS) that I submitted for WG21 review.

P2901R0 (Batched BLAS) final submission

---

D1673/D1673R13-running-revision.html
D1673/P1673.md

P1673: More Kona updates (2023/11/09)

P1673: More Kona updates (2023/11/09)

---

layout_padded/P2642R6.html
layout_padded/layout_padded.md

Address LWG's 2024/01/17 review feedback on P2642 (padded mdspan layouts).

P2642: Address LWG's 2024/01/17 review feedback
